### ISSUE TITLE
Date handling numerical precision

### ISSUE THREAD

**Issue by groutr** [NOAA-EMC/atm-blending#1]
Matlab appears to lack enough precision to properly resolve the epoch date calculations. This leads to some ever-so-slightly-off dates.

Example:
We end up with dates like 2018-09-01 12:59:59.999997 instead of 2018-09-01 13:00. The problem seems to be matlab missing digits.
```
# matlab's result to final.time-726834 (as computed in blending_routine_hwrf.m)
10470.5416666666  # resolves to (2018, 9, 1, 12, 59, 59, 999994)

# python's result
10470.541666666666  # resolves to (2018, 9, 1, 13, 0, 0, 0)
```
@aliabdolali, is there a way to fix this?

**Comment by aliabdolali** [comment]
@groutr think so, I'll make the changes and will create one netcdf file, to make sure it is solved and once approved, I'll regenerate the entire files.

**Comment by aliabdolali** [comment]
I have modified the time reference and time unit in the netcdf outputs, so it is seconds since the genesis of the hurricane.
